---
server:
    port: 5001
    host: 0.0.0.0

app:
  default_groups_test_files:
      - shared_regression_testng
      - mat_APIGW_testng
      - extended_mat_7a_APIGW_testng
      - extended_mat_7b_APIGW_testng
      - extended_mat_APIGW_testng
      - extended_mat_2_APIGW_testng
      - extended_mat_3_APIGW_testng
      - extended_mat_4_APIGW_testng
      - extended_mat_5_APIGW_testng
  supported_groups:
    oc-cd-group4:
      cluster: ilocpde456
      project: DIGOC
      url: http://illin5565:18080/job/oc-cd-group4/job/oc-cd-group4/
      test_files:
        - group4_integration_tests_testng
        - grp4_integration_to_CT_testng
        - ContratedOffer_tests_testng
        - ContratedOffer_Pack_testng
        - Everest_Configurator_Pack_testng
        - Everest_Qualification_Pack_testng
        - Everest_validator_pack
        - Olympus_pack_testng
        - Everest_Validator_Dependency_Rules_Pack_testng
        - Fuji_Price_Pack_testng
        - Fuji_Promotion_Pack_testng
        - Fuji_Replace_Pack_testng
        - mat_oc_product_configurator_hooks_APIGW_testng
    oc-cd-group3:
      cluster: ilocpde456
      project: DIGOC
      url: http://illin5565:18080/job/oc-cd-group3/job/oc-cd-group3/
      test_files:
        - banshee_testng
        - search_regression_testing
        - pii_regression_testng
        - conflictresolution_regression_testng
        - group2_regression_testng
        - payment_regression_testng
        - inflight_promotion_regression_testng
        - deliver_regression_testng
        - contributing_regression_testng
        - terminate_suspend_regression_testng
        - site_managment_regression_testng
        - future_regression_testng
        - amend_regression_testng
        - b2b_ct_regression_testng
  supported_services:
    productconfigurator-subdomain:
      repo_label: productconfigurator-subdomain
      project: DIGOC
      related_group: oc-cd-group4
    productconfigurator-subdomain-api:
      repo_label: productconfigurator-subdomain-api
      project: DIGOC
      related_group: oc-cd-group4
    productconfigurator:
      repo_label: productconfigurator-ms
      project: DIGOC
      related_group: oc-cd-group4
    productconfigurator-action:
      repo_label: productconfigurator-action-ms
      project: DIGOC
      related_group: oc-cd-group4
    productconfigurator-commitmentterm:
      repo_label: productconfigurator-commitmentterm-ms
      project: DIGOC
      related_group: oc-cd-group4
    productconfigurator-mergeentities:
      repo_label: productconfigurator-mergeentities-ms
      project: DIGOC
      related_group: oc-cd-group4
    productconfigurator-pioperations:
      repo_label: productconfigurator-pioperations-ms
      project: DIGOC
      related_group: oc-cd-group4
    productconfigurator-price:
      repo_label: productconfigurator-price-ms
      project: DIGOC
      related_group: oc-cd-group4
    productconfigurator-promotion:
      repo_label: productconfigurator-promotion-ms
      project: DIGOC
      related_group: oc-cd-group4
    productconfigurator-qualification:
      repo_label: productconfigurator-qualification-ms
      project: DIGOC
      related_group: oc-cd-group4
    productconfigurator-replace:
      repo_label: productconfigurator-replace-ms
      project: DIGOC
      related_group: oc-cd-group4
    productvalidator:
      repo_label: productvalidator-ms
      project: DIGOC
      related_group: oc-cd-group4
    productorder-subdomain:
      repo_label: productorder-subdomain
      project: DIGOC
      related_group: oc-cd-group3
    productorder-subdomain-api:
      repo_label: productorder-subdomain-api
      project: DIGOC
      related_group: oc-cd-group3
    productorder-futurelauncher:
      repo_label: productorder-futurelauncher-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-limiteddurationproduct:
      repo_label: productorder-limiteddurationproduct-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-modifyorder:
      repo_label: productorder-modifyorder-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-paymentorder:
      repo_label: productorder-paymentorder-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-price:
      repo_label: productorder-price-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-productorder:
      repo_label: productorder-productorder-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-submitorder:
      repo_label: productorder-submitorder-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-validateorder:
      repo_label: productorder-validateorder-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-prepaidorder:
      repo_label: productorder-prepaidorder-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-manage:
      repo_label: productorder-manage-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-search:
      repo_label: productorder-search-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-archive:
      repo_label: productorder-archive-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-notification:
      repo_label: productorder-notification-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-inflight:
      repo_label: productorder-inflight-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-conflictresolution:
      repo_label: productorder-conflictresolution-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-deliverproductorder:
      repo_label: productorder-deliverproductorder-ms
      project: DIGOC
      related_group: oc-cd-group3
    productorder-amendorder:
      repo_label: productorder-amendorder-ms
      project: DIGOC
      related_group: oc-cd-group3

nexus:
  index_data_repository: ms-helm-release
  nexus_search_endpoint: "https://illin5589.corp.amdocs.com:28081/service/rest/v1/search"

smart_client:
  base_url: https://amd-apigw-stack-service-oc-cd-ml-devops-lighttracer.apps.ilocpde548.ocpd.corp.amdocs.com/lightTracer/v1
  smart_tests_all_endpoint: /smart-tests-all
  smart_tests_statistics_endpoint: /smart-tests-statistics

logging:
  log_level: INFO
  log_file_name: app.log

cache:
  get_all_endpoint:
    ttl: 600
    enabled: true
  smart_analyze_endpoint:
    ttl: 600
    enabled: true